source 'http://rubygems.org'

gem 'rails', '>= 3.0.0', '< 3.1.0'
gem 'rdoc'
gem 'mysql2', "< 0.3.0"
gem 'verification'

gem 'country_select'

group :test do
  gem "shoulda"
  gem 'timecop'
  gem "mocha", '!= 0.13.0', '!= 0.13.1', '!= 0.13.2'
  gem "factory_girl"
end

gem "massassignment_security_form", '1.0', :path => '../../../'
